name: Deploy Hugo Website

# https://github.com/peaceiris/actions-gh-pages
# https://github.com/actions/starter-workflows/tree/main/pages

on:
  push:
    branches: [ "trunk" ]
    paths:
      - 'docs/**'
      - '.github/**'
  workflow_dispatch: # Allows workflow manually run from Actions Tabs

# Sets permissions of GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment task.
concurrency:
  cancel-in-progress: true
  # 用户名/仓库名/.github/workflows/当前文件名.yml@refs/heads/分支名
  group: ${{ github.workflow_ref }}

defaults:
  run:
    shell: bash

jobs:
  xwlc-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: peaceiris/actions-hugo@v3
        with:
          extended: true
          hugo-version: 'latest'
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          # The action defaults to search for dependency files package-lock.json
          # in the repository root, and uses its hash as a part of the cache key.
          # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-data
          cache-dependency-path: '**/package-lock.json'
      - run: .github/actions/update-website.sh
      - run: cd docs && npm clean-install
      - run: cd docs && make release-deploy
      - uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/public'

  xwlc-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: xwlc-build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
