name: Deploy Hugo Website

# https://github.com/peaceiris/actions-gh-pages
# https://github.com/actions/starter-workflows/tree/main/pages

on:
  push:
    branches: [ "trunk" ]
    paths:
      - 'docs/**'
      - 'main/**'
      - '.github/**'
  workflow_dispatch: # Allows workflow manually run from Actions Tabs

# Sets permissions of GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment task.
concurrency:
  cancel-in-progress: true
  # 用户名/仓库名/.github/workflows/当前文件名.yml@refs/heads/分支名
  group: ${{ github.workflow_ref }}

defaults:
  run:
    shell: bash

jobs:
  xwlc-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          #submodules: true
      - uses: peaceiris/actions-hugo@v3
        with:
          extended: true
          hugo-version: 'latest'

      - uses: actions/configure-pages@v5
      - run: |
          .github/actions/update-website.sh
      - uses: actions/upload-pages-artifact@v3
        with:
          path: './docs'

  xwlc-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: xwlc-build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
